/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.project_2.GUI;

import com.example.project_2.BLL.ThanhVienBLL;
import com.example.project_2.BLL.ThietBiBLL;
import com.example.project_2.BLL.ThongTinSDBLL;
import com.example.project_2.DTO.ThongTinSD;
import com.example.project_2.components.dialogs.MuonThietBiDialog;
import com.example.project_2.components.dialogs.TraThietBiDialog;
import com.example.project_2.components.table.EventAction;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Hung
 */
public class QLTVMuonTraThietBiGUI extends javax.swing.JPanel {
    private final ThongTinSDBLL thongTinSDBLL = new ThongTinSDBLL();
    private final ThanhVienBLL thanhVienBLL = new ThanhVienBLL();
    private final ThietBiBLL thietBiBLL = new ThietBiBLL();
    private final EventAction<ThongTinSD> eventAction = new EventAction<ThongTinSD>() {
        @Override
        public void delete(ThongTinSD student) {
            // TODO
        }

        @Override
        public void update(ThongTinSD student) {

        }
    };

    /**
     * Creates new form ThanhVienGUI
     */
    public QLTVMuonTraThietBiGUI() {
        initComponents();
        setOpaque(false);

        loadData();
    }

    public void loadData() {
        String searchText = txtSearch.getText().trim();
        Map<String, Object> criteria = new HashMap<>();
        if (!searchText.isBlank()) {
            criteria.put("HoTen", searchText);
            criteria.put("TenTB", searchText);
        }
        List<ThongTinSD> thongTinSDList = thongTinSDBLL.getThongTinSDMuonTra(criteria);
        setTableThongTinSD(thongTinSDList);
    }

    public void setTableThongTinSD(List<ThongTinSD> thongTinSDList) {
        table.removeAllRow();

        for (var thongTinSD : thongTinSDList) {
            String state;
            if (thongTinSD.getTGTra() != null) {
                state = "Đã trả";
            } else if (thongTinSD.getTGDatcho() != null) {
                state = "Đã đặt chỗ";
            } else {
                state = "Đang mượn";
            }
            table.addRow(new Object[]{
                    thongTinSD.getThanhVien().getHoTen(),
                    thongTinSD.getThietBi().getTenTB(),
                    thongTinSD.getTGDatcho(),
                    thongTinSD.getTGMuon(),
                    thongTinSD.getTGTra(),
                    state
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new com.example.project_2.components.swing.Button();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new com.example.project_2.components.swing.TextField();
        btnSearch = new com.example.project_2.components.swing.Button();
        btnMuon = new com.example.project_2.components.swing.Button();
        btnTra = new com.example.project_2.components.swing.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new com.example.project_2.components.table.Table();

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(159, 159, 159));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mượn - trả thiết bị");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N

        btnMuon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMuon.setText("Mượn");
        btnMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonActionPerformed(evt);
            }
        });

        btnTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTra.setText("Trả");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{
                        "Tên sinh viên", "Tên thiết bị", "Thời gian đặt chỗ", "Thời gian mượn", "Thời gian trả", "Trạng thái"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnTra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonActionPerformed
        MuonThietBiDialog modal = new MuonThietBiDialog(Main.getFrames()[0], true);
        modal.showDialog();

        if (modal.isOk()) {
            Main.recreateGUI(new QLTVMuonTraThietBiGUI());
        }
    }//GEN-LAST:event_btnMuonActionPerformed

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        TraThietBiDialog modal = new TraThietBiDialog(Main.getFrames()[0], true);
        modal.showDialog();

        if (modal.isOk()) {
            Main.recreateGUI(new QLTVMuonTraThietBiGUI());
        }
    }//GEN-LAST:event_btnTraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnMuon;
    private com.example.project_2.components.swing.Button btnSearch;
    private javax.swing.JButton btnTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.example.project_2.components.table.Table table;
    private com.example.project_2.components.swing.TextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
